### ISSUE TITLE
Error running: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder" and Exception in thread "main" java.net.BindException: Address already in use: bind

### ISSUE THREAD

**Issue by aderchox** [andrewlalis/Concord#6]
Hi Andrew Lalis, please see this:
```
PS D:\Downloads> java -jar .\concord-server.jar
server-config.json does not exist. Creating it with initial values. Edit and restart to apply changes.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Adding index on "timestamp" field to collection channel-95a19ca9-d368-4948-a49c-a269d17bb2c6
Adding index on "senderNickname" field to collection channel-95a19ca9-d368-4948-a49c-a269d17bb2c6
Adding index on "message" field to collection channel-95a19ca9-d368-4948-a49c-a269d17bb2c6
Exception in thread "main" java.net.BindException: Address already in use: bind
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Net.java:555)
        at java.base/sun.nio.ch.Net.bind(Net.java:544)
        at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643)
        at java.base/java.net.ServerSocket.bind(ServerSocket.java:388)
        at java.base/java.net.ServerSocket.<init>(ServerSocket.java:274)
        at java.base/java.net.ServerSocket.<init>(ServerSocket.java:167)
        at nl.andrewl.concord_server.ConcordServer.<init>(ConcordServer.java:85)
        at nl.andrewl.concord_server.ConcordServer.main(ConcordServer.java:231)
PS D:\Downloads> java -jar .\concord-server.jar
Loaded configuration from server-config.json
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.net.BindException: Address already in use: bind
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Net.java:555)
        at java.base/sun.nio.ch.Net.bind(Net.java:544)
        at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643)
        at java.base/java.net.ServerSocket.bind(ServerSocket.java:388)
        at java.base/java.net.ServerSocket.<init>(ServerSocket.java:274)
        at java.base/java.net.ServerSocket.<init>(ServerSocket.java:167)
        at nl.andrewl.concord_server.ConcordServer.<init>(ConcordServer.java:85)
        at nl.andrewl.concord_server.ConcordServer.main(ConcordServer.java:231)
```
I'm using in case it matters:
```
openjdk 17 2021-09-14
OpenJDK Runtime Environment Temurin-17+35 (build 17+35)
OpenJDK 64-Bit Server VM Temurin-17+35 (build 17+35, mixed mode, sharing)
```
Am I doing something wrong?

**Comment by andrewlalis** [comment]
Yes, it looks like you're trying to start the program on a port which is in use. Check the config file and set it to a port that isn't already being used.

**Comment by aderchox** [comment]
Oh I changed the port to 8120 and it works now.
